/* Generated by scripts/sync-env.cjs — do not edit by hand */
export const envOverrides = {
  solanaRpcUrl: "https://rpc.shyft.to/?api_key=UVpm0NJUQWYhEUIY",
  claimySplMintAddress: "CVNAP5GpSBVQfqtqfu4jVRMVYmTKBqS5a5mDMPFUpump",
  supabaseUrl: "https://mosmjagamrtsyeoohcty.supabase.co",
  supabaseAnonKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vc21qYWdhbXJ0c3llb29oY3R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5NzYxOTQsImV4cCI6MjA4OTU1MjE5NH0.1NUfVb3kOMhqJfeE_DxG0YFu7g9TFs7K4ZnuQqBMaWo"
};
