/**
 * Reads project root `.env` or `claimy.env` and writes `src/environments/env.overrides.ts`.
 * Variables: CLAIMY_SUPABASE_URL, CLAIMY_SUPABASE_ANON_KEY, CLAIMY_SOLANA_RPC_URL, CLAIMY_SPL_MINT
 *
 * Setup: copy `env.template` to `.env`, fill in values, run this script.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');

function resolveEnvFile() {
  for (const name of ['.env', 'claimy.env']) {
    const p = path.join(root, name);
    if (fs.existsSync(p)) return p;
  }
  return null;
}

const envFile = resolveEnvFile();
if (envFile) {
  require('dotenv').config({ path: envFile });
}

const rpc = (process.env.CLAIMY_SOLANA_RPC_URL || '').trim();
const mint = (process.env.CLAIMY_SPL_MINT || '').trim();
const supa = (process.env.CLAIMY_SUPABASE_URL || '').trim();
const supaAnon = (process.env.CLAIMY_SUPABASE_ANON_KEY || '').trim();
const content = `/* Generated by scripts/sync-env.cjs — do not edit by hand */
export const envOverrides = {
  solanaRpcUrl: ${JSON.stringify(rpc)},
  claimySplMintAddress: ${JSON.stringify(mint)},
  supabaseUrl: ${JSON.stringify(supa)},
  supabaseAnonKey: ${JSON.stringify(supaAnon)}
};
`;

const outPath = path.join(root, 'src', 'environments', 'env.overrides.ts');
fs.writeFileSync(outPath, content, 'utf8');
if (envFile) {
  console.log('Wrote src/environments/env.overrides.ts from', path.basename(envFile));
} else {
  console.log('No .env or claimy.env — wrote empty overrides. Copy env.template to .env and run again.');
}
